### ISSUE TITLE
[Issue] Large Html text sent through LoadHtml(html);

### ISSUE THREAD

**Issue by BrandonMayjeye** [Voltstro-Studios/UnityWebBrowser#355] opened 2024-10-17 18:51 UTC
### What platform are you experiencing this issue on?

Linux x64

### What version of UWB are you using?

2.2.2

### What Unity version are you running?

2022.3.48f1

### Describe what the issue you are experiencing is.

Hello, Yesterday you resolved an issue that was very similar to this , 
It fixed it for that particular case, however when i started adding more data to the function i ran into a new issue.
Looks like the socket gets closed before it completes the sending of the whole string

[the other ticket is here](https://github.com/Voltstro-Studios/UnityWebBrowser/issues/351)

I may have found the limitations of this function , and am working on loading the page and getting data back from unity to fill it in so there's no urgency here. this function is used more for quick output for me.

```
[UWB]: Error in data loop! System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
  at System.Net.Sockets.Socket.Receive (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags) [0x00016] in <1878a84e5d5c42539d36f7fca65b9685>:0 
  at System.Net.Sockets.NetworkStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 size) [0x00065] in <1878a84e5d5c42539d36f7fca65b9685>:0 
   --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 size) [0x000ac] in <1878a84e5d5c42539d36f7fca65b9685>:0 
  at VoltRpc.IO.BufferedReader.ReadStream (System.Int32 neededSize) [0x00031] in <d188448691a844539fe4e130c3567971>:0 
  at VoltRpc.IO.BufferedReader.ReadBlittable[T] () [0x0001b] in <d188448691a844539fe4e130c3567971>:0 
  at VoltRpc.IO.BufferedReader.ReadByte () [0x00000] in <d188448691a844539fe4e130c3567971>:0 
  at VoltRpc.Communication.Client.InvokeMethod (System.String methodName, System.Object[] parameters) [0x000c6] in <d188448691a844539fe4e130c3567971>:0 
  at VoltstroStudios.UnityWebBrowser.Shared.Core.EngineControls.GetPixels () [0x00000] in /_/src/VoltstroStudios.UnityWebBrowser.Shared/obj/GeneratedFiles/VoltRpc.Proxy.Generator/VoltRpc.Proxy.Generator.ProxyGenerator/EngineControls.cs:30 
  at VoltstroStudios.UnityWebBrowser.Core.WebBrowserCommunicationsManager.GetPixels () [0x00020] in ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.2.2/Runtime/Core/WebBrowserCommunicationsManager.cs:100 
  at VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient.PixelDataLoop () [0x0009d] in ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.2.2/Runtime/Core/WebBrowserClient.cs:574 
UnityEngine.Logger:LogError (string,object)
VoltstroStudios.UnityWebBrowser.Logging.DefaultUnityWebBrowserLogger:Error (object) (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.2.2/Runtime/Logging/DefaultUnityWebBrowserLogger.cs:36)
VoltstroStudios.UnityWebBrowser.Core.WebBrowserClient:PixelDataLoop () (at ./Library/PackageCache/dev.voltstro.unitywebbrowser@2.2.2/Runtime/Core/WebBrowserClient.cs:591)
System.Threading.ThreadHelper:ThreadStart ()


```

the text that generates the error is below.

[test.txt](https://github.com/user-attachments/files/17421154/test.txt)

### Provide reproducible steps for this issue.

Execute the .LoadHtml function on the browser and pass in the string in the txt file as input.

**Comment by Voltstro** [comment] 2024-10-20 08:43
Issue was with VoltRpc not handling large strings very well, it was fixed in VoltRpc 3.2.1, which UWB release 2.2.3 uses. Issue was actually being caused by UWB calling either `OnUrlChanged`, `OnLoadStart` or `OnLoadFinish` with the very large URL that gets formed by `LoadHtml`.

There still is a limit on how large a string can be, but it should be quite large now.

**Closed by Voltstro** 2024-10-20 08:43 UTC
Labels: issue
