### ISSUE TITLE
[Issue] Problems With Dropdowns? 

### ISSUE THREAD

**Issue by Tompisom** [Voltstro-Studios/UnityWebBrowser#324] opened 2024-08-23 15:08 UTC
### What platform are you experiencing this issue on?

Windows

### What architecture is your platform?

64-Bit

### What version of UWB are you using?

Latest VoltstroUPM Release

### What Unity version are you running?

2021.3.21f1

### Describe what the issue you are experiencing is.

Dropdown Dont Work

### Provide reproducible steps for this issue.

So I create a Canvas with a RawImage, and added the WebBrowserBasic to the RawImage, This is my WebBrowserBasic Inspector.
![image](https://github.com/user-attachments/assets/e04a5a2f-0b64-4864-b668-96dd9f6789fc). Everything worked fine input txt, scrolling, navegation, until I faced this isseu with Dropdowns. Did I configure something wrong? 

### Any additional info you like to provide?
![94030e1a2dcc93a61209a8d57c50ac35](https://github.com/user-attachments/assets/01b9fc5f-04b8-47b4-94f4-d25685d6c2b1)

**Comment by Voltstro** [comment] 2024-08-30 12:54
Duplicate of #314.

**Closed by Voltstro** 2024-08-30 12:54 UTC
Labels: issue
